jobs:
    include:
        - language: c
          compiler: gcc
          os: linux
          script:
              - ./build-tests.sh
              - ./run-tests.sh
        - language: c
          compiler: gcc
          os: osx
          script:
              - ./build-tests.sh
              - ./run-tests.sh
