jobs:
    include:
        - language: c
          compiler: gcc
          os: linux
          script:
              - ./build-tests.sh
              - ./dist/unit-tests > /dev/null 2>&1
        - language: c
          compiler: gcc
          os: osx
          script:
              - ./build-tests.sh
              - ./dist/unit-tests > /dev/null 2>&1
