jobs:
    include:
        - language: c
          compiler: gcc
          os: linux
          script:
              - make
              - ./test
        - language: c
          compiler: gcc
          os: osx
          script:
              - make
              - ./test
