jobs:
    include:
        - language: c
          compiler: gcc
          os: linux
          script:
              - make
              - ./test > /dev/null 2>&1
        - language: c
          compiler: gcc
          os: osx
          script:
              - make
              - ./test > /dev/null 2>&1
